// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATAlu02IXFKOXUK9mASSRUk0xt7ay2FqM',
    appId: '1:512122618629:web:8f9e3b30569b275fd8ed6c',
    messagingSenderId: '512122618629',
    projectId: 'pingolearn-c22bd',
    authDomain: 'pingolearn-c22bd.firebaseapp.com',
    storageBucket: 'pingolearn-c22bd.appspot.com',
    measurementId: 'G-JYZG087KHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW8rUD4xEdWAOPjM4f8Au9G2VUhhTfp4E',
    appId: '1:512122618629:android:3e723aa8f609662ed8ed6c',
    messagingSenderId: '512122618629',
    projectId: 'pingolearn-c22bd',
    storageBucket: 'pingolearn-c22bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWy43U8Gq0BOPGBtcHBuQRMef-vvUZNR0',
    appId: '1:512122618629:ios:926f9f945c1d42a3d8ed6c',
    messagingSenderId: '512122618629',
    projectId: 'pingolearn-c22bd',
    storageBucket: 'pingolearn-c22bd.appspot.com',
    iosBundleId: 'com.example.pingolearn',
  );
}
